Scraper
sdes-team/knightlife pull request #27
Opened 2023-10-18 17:11 UTC by kitorer

* The db files are just for testing, we haven't made any decisions on hosting yet.
* Just pulling jsons from events.ucf

2023-10-18 17:19 UTC, rob-3 commented
Can you pull latest main and then `git rebase main` this? (Or use the "rebase branch" option on GitHub)

2023-10-18 18:13 UTC, rob-3 requested changes
Looks good overall, but the first backend PR raises some questions we should think about (won't block merge though).

* Do we store the entire JSON from other sources in another TEXT DB field? It'll be difficult to reconstruct that data later if we need it. I think we probably want to save it, if only for helping to deduplicate later on.
* How are we going to schedule scraping? I'm thinking that for now, a python script that runs the jobs on some schedule probably is simplest. Not sure how that will scale up to things like IG though

Good work, if you fix the blocking issues this can go in :)

2023-10-21 13:16 UTC, rob-3 commented
To update this you want the "update with rebase" option on GitHub, or
```bash
git switch main
git pull
git switch scraper
git rebase main
git push --force-with-lease
```

2023-10-22 03:45 UTC, rob-3 commented
Did you have issues getting the uuid() function calls in SQLite to work? It's perfectly ok to do it from python but the SQLite version should work if you have a recentish SQLite and it saves some work.

2023-10-22 07:03 UTC, kitorer commented
yeah I did, but I'm also not on the most recent version of python rn. I can try that tho

2023-10-22 13:32 UTC, rob-3 commented
It's almost certainly an old SQLite version. Try installing the most recent build of SQLite if you want. Otherwise, the python solution is fine

2023-10-22 15:50 UTC, rob-3 requested changes

2023-10-22 15:50 UTC, rob-3 commented on repos/scrapers/UCF_events.py
> +            description TEXT
blocking: Missing comma

2023-10-22 15:50 UTC, rob-3 commented on repos/scrapers/UCF_events.py
> +        cursor.execute('INSERT INTO events (id, title, description, url, starts, ends  ) VALUES (?, ?, ? ,? ,? ,?)',
nit: random space after `ends`

2023-10-22 15:53 UTC, rob-3 commented
If you rebase this onto main and force push, I will approve it!

2023-10-22 15:56 UTC, rob-3 approved these changes

2023-10-22 15:56 UTC, merged