Event Page
sdes-team/knightlife pull request #36
Opened 2023-10-26 00:27 UTC by rikimbili

2023-10-26 17:35 UTC, rob-3 requested changes
I'm ignoring code in the `components/` directory as shadcn library code, but please lmk if it's something you've written/modified.

2023-10-26 17:35 UTC, rob-3 commented on repos/web/src/routes/+page.svelte
> +  <h1 class="mt-8 text-xl font-bold">Data fetched from Express backend:</h1>
unrelated: to simplify the backend deployment, I want to make the port for any backends to be configurable. I think we can just remove the express one though; for what we're doing I don't think the SvelteKit app should be synchronizing with the backend other than via DB calls.

2023-10-26 17:35 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +        <span class={data.event.location && "text-muted-foreground"}>{data.event.address}</span>
nonblocking: There's a builtin in svelte for conditional classes that is sometimes nice:
```svelte
<span class:text-muted-foreground={data.event.location}>{data.event.address}</span>
```

2023-10-26 17:35 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <EventDescription description={data.event.description} />
nonblocking: Maybe it's not how shadcn works, but I feel like this component should just be copy-pasted inline. Where else would I use an `EventDescription` anyway?

2023-10-26 21:47 UTC, rikimbili commented on packages/types/src/db.ts
> +  tags: string | null;
This is something that we are going to have to experiment with. We can probably handpick a couple dozen tags and then feed it to ChatGPT, telling it to use the tags and assign Y number of tags to X event based on the description.

2023-10-26 21:47 UTC, rikimbili commented on repos/web/src/lib/components/ui/separator/index.ts
> +	Root as Separator
No clue, this is all part of shadcn

2023-10-26 21:49 UTC, rikimbili commented on repos/web/src/lib/components/ui/separator/index.ts
> +	Root as Separator
I recommend we ignore everything inside of components/ui as that is where shadcn components are located.

2023-10-26 21:50 UTC, rikimbili commented on repos/web/src/routes/+page.svelte
> +  <h1 class="mt-8 text-xl font-bold">Data fetched from Express backend:</h1>
Sounds good

2023-10-26 21:53 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.server.ts
> +        description: sanitizeHTML(event.description)
It should, but if the database is compromised the html might be dangerous

2023-10-26 21:55 UTC, rikimbili commented on repos/web/src/utils/event.ts
> +  const titleCase = (str: string) => str.split(" ").map(capitalize).join(" ");
I agree, although we might have to remove this function altogether considering that we are no longer going to use comma-separated strings for tags

2023-10-26 22:38 UTC, rikimbili commented on repos/web/svelte.config.js
> +      $utils: "./src/utils"
I dont think you can get it to work in Svelte using tsconfig. In Next.js it is as simple as adding the aliases to the tsconfig file

2023-10-26 22:39 UTC, rob-3 commented
There are conflicts rn, can you rebase or merge to fix them conflicts?

2023-10-26 22:39 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +<main class="flex h-full w-full max-w-7xl flex-col gap-4 p-4 sm:gap-6">
We are, they classes are sorted (based on semantical order not alphabetical) https://tailwindcss.com/blog/automatic-class-sorting-with-prettier#how-classes-are-sorted

2023-10-26 22:41 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +    <Button variant="outline" size="sm" class="w-fit">Add to Calendar</Button>
Even if we were to make our own component, we would want to enforce these if we want our design to be consistent. Of course, for one offs we can simply modify the css by adding custom classes like how I'm doing here with w-fit

2023-10-26 22:42 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +    {#if data.event.location || data.event.address}
Yes, we can have both, either or none as we discussed today

2023-10-26 22:43 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +        <span class={data.event.location && "text-muted-foreground"}>{data.event.address}</span>
oh, I wasn't aware of that, nice. I still think we should leave it like it is in case that we want to add more classes to the string (It looks cleaner and we get sorting)

2023-10-26 22:44 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <EventDescription description={data.event.description} />
For the event feed. I plan to use this for the individual cards.

2023-10-27 00:36 UTC, rob-3 commented on repos/web/src/utils/event.ts
> +}
nit: noticed this on the second pass, but functions that take `X | null` I think often should just take `X` and push the null question up to their caller. Also, could we not just use empty string/empty JSON array for the empty tagset? It would save us saving to deal with null here

2023-10-27 00:38 UTC, rob-3 approved these changes

2023-10-27 00:38 UTC, merged