Draft PR: Push notifications (not done do not merge)
sdes-team/knightlife pull request #39
Opened 2023-10-30 04:09 UTC by fabriUCF

2023-10-30 04:15 UTC, fabriUCF commented on repos/web/src/routes/api/push/+server.ts
> +export async function GET({ url }) {
This needs to be a POST request. Just wanted to make sure this worked

2023-10-30 19:27 UTC, rob-3 commented
I like the direction this is going! I think instead of an endpoint we probably want a utility function in the `lib/server` folder. The keys also need to be rotated and put in environment variables.

2023-10-30 19:28 UTC, rob-3 commented
The button actually makes sense for testing rn though

2023-10-30 19:29 UTC, rikimbili commented
> I like the direction this is going! I think instead of an endpoint we probably want a utility function in the `lib/server` folder. The keys also need to be rotated and put in environment variables.

I just realized that I've been writing utility and server helper functions outside of lib. I just read the Svelte docs and they recommend using lib for this to keep it organized.

2023-11-01 16:02 UTC, rob-3 requested changes
"suggestion:" means consider it, but no change is required.
"blocking:" means a change is required

2023-11-01 16:02 UTC, rob-3 commented on repos/web/src/routes/playground/+page.svelte
> +      return subscribed;
blocking: If I understand correctly, I think this `return` is unnecessary.

2023-11-01 18:20 UTC, rob-3 requested changes

2023-11-02 04:38 UTC, rob-3 approved these changes

2023-11-02 04:38 UTC, rob-3 commented on repos/web/src/routes/playground/+page.svelte
> +        return subscribed;
nit: you can actually do the assignment in the next `.then` to avoid this await

2023-11-02 05:16 UTC, merged