Knight connect
sdes-team/knightlife pull request #45
Opened 2023-10-31 05:17 UTC by kitorer

KAN-34

2023-10-31 17:26 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +from helpers.time_now import encoded_time #this function is from PR44 remove this comment when merged
no action required: What you can do in the future is just branch this branch off of PR 44 and then put something to the effect of "Depends on #44" in the PR description.

blocking: replace this with the oneliner mentioned in #44

2023-10-31 17:29 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +            cursor.executescript(f.read())
blocking: I think this inits the database, but we shouldn't need to do this on every fetch. You can just assume the database is there, but if you want to make it more robust, check if the database is there before you open it.

2023-10-31 17:33 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +            for event in headers:
blocking: This works, but is a little strange. It will also break if they ever add any other fields to their JSON. Why not just:
```python3
events = data.value
for event in events:
  # ...

2023-10-31 17:34 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +                new_uuid = str(uuid.uuid4())
nonblocking: this will need to change if we use cuids.
blocking: put a TODO to swap this to cuids at some point

2023-10-31 17:36 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +                encoded_time(),
blocking: Same as in #44, I think this should be put in a variable and reused.

2023-10-31 17:37 UTC, rob-3 requested changes
Some minor improvements, mostly looks great!

2023-10-31 22:37 UTC, kitorer commented on repos/scrapers/KnightConnect.py
> +            for event in headers:
I agree, I'll go back and make this better later, there's almost certainly a better way

2023-10-31 22:54 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +            for event in headers:
There is, just do
```python3
for event in data["value"]:
```
and remove all the checks!

2023-10-31 22:56 UTC, kitorer commented on repos/scrapers/KnightConnect.py
> +            for event in headers:
I got it!

2023-10-31 22:56 UTC, kitorer commented on repos/scrapers/KnightConnect.py
> +                new_uuid = str(uuid.uuid4())
Ok, ill put this in jira

2023-10-31 23:52 UTC, rob-3 requested changes

2023-10-31 23:52 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +        with open(root / 'schemas.sql', 'r') as f:
blocking: no need to open the schema if we're not using it :)

2023-11-01 17:51 UTC, rob-3 requested changes

2023-11-01 17:51 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +encoded_time = datetime.now().isoformat()
blocking: why wouldn't we put this in the function? This will only grab the time on the first import.

2023-11-01 18:13 UTC, rob-3 commented
This can be approved once #45 goes in.

2023-11-06 22:29 UTC, rob-3 approved these changes

2023-11-06 22:46 UTC, merged