Remove duplicates
sdes-team/knightlife pull request #53
Opened 2023-11-08 19:46 UTC by kitorer

I don't for see us using the search score that is assigned to each event in knight connect. So, I removed that. it was the only thing that would change for the same events. 

This needs to be tested over a time period of course.

2023-11-08 19:57 UTC, rob-3 requested changes
This approach is too brittle. If we check event uniqueness based on the entire JSON, if anything gets updated at the source (typo fix in description or name change), we'll create a duplicate event.

What we should do is deduplicate on the `id` field provided by KnightConnect and the similar `eventinstance_id` in the UCF events. We also should be updating the existing entry if the upstream has changed (upsert or `REPLACE`).

2023-11-08 21:39 UTC, rikimbili commented
I think that what we would want to do eventually is incorporate some model that can do a similarity comparison for any newly scraped event against all existing events. 

We can use a vector database or a database that supports vectors like Postgres with [pgvector](https://github.com/pgvector/pgvector) to vectorize all events. To compare, we just query for the top one most similar event and get a similarity score for each using a sentence similarity model: https://huggingface.co/tasks/sentence-similarity or https://www.sbert.net/docs/usage/semantic_textual_similarity.html.

This approach would be independent of the way that the original data was scraped. We don't need to have a source event id.

2023-11-08 22:06 UTC, rob-3 commented
I agree, but we need something now just to get the backend working, and it's low-hanging-fruit to just compare the IDs.

2023-11-10 04:04 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +                               event['id']
blocking: These need to have the source name prepended, otherwise there could be duplicates across different sources.

2023-11-10 04:04 UTC, rob-3 commented on repos/scrapers/KnightConnect.py
> +        for event in data['value']:
Random space?

2023-11-10 04:05 UTC, rob-3 requested changes
See blocking issue. If you fix that it can go in. Otherwise this looks great!

2023-11-11 17:51 UTC, rob-3 commented on repos/scrapers/UCF_events.py
> +                               f'events.ucf-{event["id"]}'
Have you looked into the difference between `eventinstance_id` `event_id` and regular old `id`? `eventinstance_id` and `id` seem to be the same in the events I'm looking at, but it's not clear to me how `event_id` is different. Maybe recurring event share an `event_id`?

2023-11-11 20:29 UTC, rob-3 commented on repos/scrapers/UCF_events.py
> +                               f'events.ucf-{event["id"]}'
Tbh this is not a blocking issue, but it is something I'm a little suspicious of

2023-11-11 20:33 UTC, rob-3 requested changes

2023-11-11 20:33 UTC, rob-3 commented on schemas.sql
> +    json_id      TEXT UNIQUE
blocking: please make this `NOT NULL` also!

2023-11-11 20:49 UTC, rob-3 approved these changes

2023-11-11 20:49 UTC, merged