Offline Queries and Events
sdes-team/knightlife pull request #57
Opened 2023-11-10 01:18 UTC by rikimbili

There are some issues with the PWA which makes this not work fully when offline. The event/[id] page is not being pre-cached and as such it doesn't work when offline. I'm not sure how to proceed, I took a quick look, but it didn't seem that straight forward for me, maybe @fabriUCF knows what to do here.

This PR just includes the basic offline support. After this, I'll be working on pagination, filtering, and a basic search.

2023-11-10 05:13 UTC, rob-3 requested changes
I'm going to bed, but will review the rest of this tomorrow morning. I figured I'd post what I'd reviewed so far

2023-11-10 05:19 UTC, rikimbili commented on repos/web/src/routes/+page.svelte
> +            .catch(() => [])) as Event["id"][]
This is what I thought was happening by using await within the array that is passed but I was like meh, this is only 2 calls anyways 😅. I'll make sure to fix this with .then

2023-11-10 05:20 UTC, rikimbili commented on repos/web/src/routes/api/events/invalid/+server.ts
> +  }
Yea I'll work on that. Do you want it to be part of this PR?

2023-11-10 05:21 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  let formattedEvent: (Omit<Event, "tags"> & { tags: string[] }) | undefined = data.event && {
I can add the type

2023-11-10 16:14 UTC, rikimbili commented on repos/web/src/routes/+page.svelte
> +      return eventIDB.event.where("id").above(0).limit(20).toArray();
Interesting, my IDE tells me that it is redundant because the function is async and we are returning a promise

2023-11-10 17:08 UTC, rob-3 commented on repos/web/src/routes/+page.svelte
> +      return eventIDB.event.where("id").above(0).limit(20).toArray();
Your ide is correct and I used to think like it, but I think the stack trace benefit is worth it and the lint rule is overzealous.

2023-11-10 17:09 UTC, rob-3 commented on repos/web/src/routes/api/events/invalid/+server.ts
> +  }
Nah, but I would like to see it before we get too many API endpoints

2023-11-10 17:14 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  let formattedEvent = data.event && formatEvent(data.event);
What do you think about putting all this formatting code into a `+page.ts`? Basically all of the JS here is just data wrangling

2023-11-10 17:44 UTC, rob-3 commented
A general comment: I would give a penny for your thoughts on the long-term strategy for SSR and caching data. For SSR, I think there's code using svelte-query for SSR, but also code using the native Svelte `+page.server.ts` and `+page.ts` files and `PageLoad`s for loading data. Is there a reason for using both?

For caching, this PR adds persistence through svelte-query's mechanism and IndexedDB, but also through manual IndexedDB calls in `onMount`. There's also the issue of offline vs online.

I am just finding it difficult to work out exactly what the intended chain of events is when a page that requires data is loaded. A diagram or written walkthrough of what you want to achieve would be awesome :)

2023-11-10 17:46 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  let formattedEvent = data.event && formatEvent(data.event);
Wouldn't that make it harder to see what's going on? I personally like having this in here considering that we are also accessing IDB and formatting the event in the .svelte page as well. Considering that page.ts runs on both the server and client, we can't put the IDB logic there, so the formatting will be split in two (an initial one in page.ts and then another one after fetching the IDB event when offline). Do you see any benefit from splitting the logic into page.ts?

2023-11-10 17:46 UTC, rob-3 commented on repos/web/src/routes/+page.svelte
> +            .catch(() => [])) as Event["id"][]
You can even extract the promises to separate vars if you like:
```ts
const promise1 = fetch(...);
const promise2 = fetch(...);
const result = await Promise.all(promise1, promise2);
```
Just don't await when you do the fetch

2023-11-10 17:47 UTC, rob-3 commented on repos/web/src/routes/+page.svelte
> +            .catch(() => [])) as Event["id"][]
Also, if you want to do it sequentially that fine too, but I'm definitely not going to approve using `Promise.all` and then still having sequential execution :)

2023-11-10 17:54 UTC, rikimbili commented
> A general comment: I would give a penny for your thoughts on the long-term strategy for SSR and caching data. For SSR, I think there's code using svelte-query for SSR, but also code using the native Svelte `+page.server.ts` and `+page.ts` files and `PageLoad`s for loading data. Is there a reason for using both?
> 
> For caching, this PR adds persistence through svelte-query's mechanism and IndexedDB, but also through manual IndexedDB calls in `onMount`. There's also the issue of offline vs online.
> 
> I am just finding it difficult to work out exactly what the intended chain of events is when a page that requires data is loaded. A diagram or written walkthrough of what you want to achieve would be awesome :)

I'm using Svelte's page.server.ts for things that can be fetched on the server beforehand. But svelte-query makes sense when the data needs to be refreshed dynamically within the svelte component (on the feed for example)

2023-11-10 18:18 UTC, rob-3 commented
In `src/routes/+page.ts`, we're using svelte-query with the `prefetchQuery` call, and this runs both on client and server since it's `+page.ts`. I feel that either we should do the svelte-query way everywhere we're doing this kind of thing, or only use it on the frontend and load data the sveltekit way for SSR.

2023-11-10 18:27 UTC, rob-3 commented
I guess the deeper problem I'm seeing is that a lot of what we're doing breaks down for meaningful offline user actions. I would like to support, for example, a user liking an event while offline. Later, when the user is back online, that like can be synchronized with the server, but in the meantime, the user should be able to see the liked event in a list on their profile page. This means that we need to track a user's liked events in a way that doesn't directly depend on server state, and I'm struggling to see how this can be easily supported.

2023-11-10 18:37 UTC, rob-3 commented
I think [Svelte stores](https://svelte.dev/docs/svelte-store) might be part of the answer, but I also think there might be a way to achieve this through the `set` functions svelte-query provides. But what I am fairly sure about is that if we mix and match things too much, it might become a pain to untangle down the line.

I would like to look into using stores as the source of truth for components, and then putting all the querying, caching, and offline stuff inside of the store. Components shouldn't have to be thinking about where their data is coming from or whether we're offline; at most they should need to handle a loading state, an error state, and the data they're given.

2023-11-10 18:37 UTC, rikimbili commented
> I guess the deeper problem I'm seeing is that a lot of what we're doing breaks down for meaningful offline user actions. I would like to support, for example, a user liking an event while offline. Later, when the user is back online, that like can be synchronized with the server, but in the meantime, the user should be able to see the liked event in a list on their profile page. This means that we need to track a user's liked events in a way that doesn't directly depend on server state, and I'm struggling to see how this can be easily supported.

I didn't know we were going to go down this path. I thought that all online features would be disabled (including liking, and any other online actions). My idea was that the offline support was meant to be a quick solution that allows you to view events but not interact with them in a meaningful way since the changes cannot be synchronized with the online server. 

In any case, what you mention seems to be part of a different system but we could still use IDB for storing pending tasks. Think of the events as static data that you download which is different from actions (liking, bookmarking, rsvping, etc). I dont think that our current approach breaks down, but rather, our current approach is separate from what we would have to do to sync offline actions with the server.

2023-11-10 18:41 UTC, rob-3 commented
I found [this talk] by Jake Archibald to be illuminating in terms of building offline-first apps. I guess we don't have to do this, but it's what I had in mind. I haven't done the best job articulating what exactly I have been thinking when I've been saying "offline".

2023-11-10 18:42 UTC, rikimbili commented
> In `src/routes/+page.ts`, we're using svelte-query with the `prefetchQuery` call, and this runs both on client and server since it's `+page.ts`. I feel that either we should do the svelte-query way everywhere we're doing this kind of thing, or only use it on the frontend and load data the sveltekit way for SSR.

Aren't we already doing it the svelte query way everywhere we use svelte query? I know there is a mix of Svelte's approach and Svelte query but that goes back to what I mentioned about static data and data that can be refetched within the client. I think we could remove the query prefetching, there is not that much benefit from doing that extra query.

2023-11-10 18:49 UTC, rob-3 commented
> I know there is a mix of Svelte's approach and Svelte query but that goes back to what I mentioned about static data and data that can be refetched within the client. I think we could remove the query prefetching, there is not that much benefit from doing that extra query.

I guess where I'm getting confused is at the difference between the data for a single event in `repos/web/src/routes/event/[slug]/+page.svelte` (loaded via `+page.server.svelte` and no endpoint/svelte-query) and the card data for the top 20 events in `repos/web/src/routes/+page.svelte` (loaded via svelte-query and an endpoint). Both can change over time, and need to be revalidated with some regularity. Neither is using any user input like a search.

2023-11-10 19:02 UTC, rikimbili commented
> > I know there is a mix of Svelte's approach and Svelte query but that goes back to what I mentioned about static data and data that can be refetched within the client. I think we could remove the query prefetching, there is not that much benefit from doing that extra query.
> 
> I guess where I'm getting confused is at the difference between the data for a single event in `repos/web/src/routes/event/[slug]/+page.svelte` (loaded via `+page.server.svelte` and no endpoint/svelte-query) and the card data for the top 20 events in `repos/web/src/routes/+page.svelte` (loaded via svelte-query and an endpoint). Both can change over time, and need to be revalidated with some regularity. Neither is using any user input like a search.

The feed page will have user input (that's what I'm going to work on next after this PR) but I don't think it makes sense to use svelte query for the event page (we could though). The only niche benefit I see is if someone leaves the tab open and comes back a significant amount of time after, svelte query will refetch it. I don't see why we would need to revalidate the single event page after the first fetch when you navigate to it. On the other hand, the feed page will need to constantly change as per user input.

2023-11-10 19:09 UTC, rob-3 commented
This makes sense to me. I guess I just don't see why we wouldn't go for the niche benefit of updating the single event in case it has been open a while. (Maybe to avoid another endpoint?)

2023-11-11 17:43 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  let formattedEvent = data.event && formatEvent(data.event);
Well, this is the intended use case for `+page.ts` (handling your data loading code), although that doesn't necessarily mean using `+page.ts` is better. You can access the data from `+page.server.ts` in `+page.ts`, and then you can actually use `if (browser)` to separate out the IDB/client only code. There's also a flag you can set per-page to make `+page.ts` always client-side if you prefer.

I think that approach is better, since it separates the HTML/CSS layout code from the data fetching code. I value the looser coupling of the layout/presentational code to the data fetching code because it makes it easier to reuse the code with other sources of data. Maybe it doesn't matter, but if we were to do something like change the app to use a persistent websocket or load data from WASM-compiled SQLite, by separating the layout from the data fetching, we can isolate changes to `+page.ts` and have confidence that the component doesn't rely on implementation details of our fetching.

Then again, the odds we'll need something like that are low, so you could argue it doesn't matter, and it probably doesn't. But hopefully that helps to explain my preference.

This is not a blocking issue for the PR, but feel free to refactor or resolve this without action as you prefer. I might take a crack at refactoring anyway it just to see what it would look like if you don't, and we can duke it out in that PR's comments later.

2023-11-11 17:49 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  let formattedEvent = data.event && formatEvent(data.event);
I'll work on refactoring this later today. Now it makes more sense, I just didn't know we could do if(browser) to run client-side only logic.

2023-11-12 21:27 UTC, rob-3 commented on repos/web/src/lib/components/QueryPersister.svelte
> +  let restoring = false;
blocking: I _think_ this variable has no real effect

2023-11-12 21:36 UTC, rob-3 commented on repos/web/src/lib/utils/conversion.ts
> +}
blocking: you've written a polyfill for [`Object.fromEntries`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries)

2023-11-12 21:41 UTC, rikimbili commented on repos/web/src/lib/utils/conversion.ts
> +}
For some reason Object.fromEntries was giving me an iterable as output instead of an object which was kind of weird. I'll try it out again

2023-11-12 21:47 UTC, rikimbili commented on repos/web/src/lib/utils/conversion.ts
> +}
It works now. Not sure what was going on, maybe I forgot to do .entries() for the search params

2023-11-12 22:07 UTC, rob-3 commented on repos/web/src/lib/server/event.ts
> +export function queryEvents({ id, sortBy, sortDir, limit = 0 }: QueryEventsParams) {
nonblocking: I feel like this function probably shouldn't exist. The reason it makes me feel weird is that the types and default interact in a way that allows nonsensical queries to happen. `queryEvents({})` doesn't work, but it typechecks. I tried to rewrite the types to make it work, but I don't think it's worth it.

I think you should either:
1. Inline it to its single call site, getting rid of the need to handle the types.
2. Split it up into a function to query by id and a function to do the other case.

I think I prefer 1 here, but no action is necessary, this just strikes me as a bit off.

2023-11-12 22:07 UTC, rob-3 commented on repos/web/src/lib/server/event.ts
> +  // Better way
Maybe this comment is talking about what I was saying above?

2023-11-12 22:10 UTC, rikimbili commented on repos/web/src/lib/server/event.ts
> +  // Better way
I dont know what happened with the comment but it was meant to say // Find a better way to do this. And yea it was referring to what you mentioned essentially

2023-11-12 22:10 UTC, rob-3 commented on repos/web/src/lib/utils/idb.ts
> +  client!: Table<PersistedClient & { id: "0" }>;
question: Does Dexie guarantee to initialize this in the `super()` call?

2023-11-12 22:11 UTC, rikimbili commented on repos/web/src/lib/utils/idb.ts
> +  client!: Table<PersistedClient & { id: "0" }>;
Yes as far as I'm aware. The assertion is there as per their docs

2023-11-12 22:19 UTC, rob-3 commented on repos/web/src/lib/query/queries.ts
> +  fetch: typeof window.fetch = window.fetch
question: Is there a specific reason we need to pass `fetch` around? I feel like I'm missing something...

2023-11-12 22:23 UTC, rikimbili commented on repos/web/src/lib/query/queries.ts
> +  fetch: typeof window.fetch = window.fetch
Yes, not for the client but when the function is executed on the server (SSR). I encountered an issue where if I used the node fetch API it would error saying that I should not be using relative paths and instead I should be using the provided (svelte fetch) function[https://kit.svelte.dev/docs/load#making-fetch-requests]. That's why I decided to take this optional dependency injection approach.

2023-11-12 22:25 UTC, rob-3 commented on repos/web/src/routes/api/events/+server.ts
> +  const parsed = schema.safeParse(Object.fromEntries(url.searchParams.entries()));
nit: According to MDN you can do `Object.fromEntries(url.searchParams)` without the `.entries()`

2023-11-12 22:25 UTC, rikimbili commented on repos/web/src/lib/server/event.ts
> +export function queryEvents({ id, sortBy, sortDir, limit = 0 }: QueryEventsParams) {
I ended up doing 1

2023-11-12 22:31 UTC, rikimbili commented on repos/web/src/routes/api/events/+server.ts
> +  const parsed = schema.safeParse(Object.fromEntries(url.searchParams.entries()));
It worked when I tried it now. Did you encounter any issues?

2023-11-12 22:33 UTC, rob-3 commented on repos/web/src/routes/api/events/+server.ts
> +});
blocking: I think the schema is more accurately this:
```ts
const schema = z.union([
  z.object({ id: z.string() }),
  z.object({ limit: z.number().int().nonnegative() }),
]);
```

2023-11-12 22:36 UTC, rob-3 commented on repos/web/src/routes/api/events/+server.ts
> +        ORDER BY ? ${orderDir}
blocking: I think there's a bug here with `orderDir`. The template string is `ORDER BY DESC DESC`

2023-11-12 22:41 UTC, rob-3 commented on repos/web/src/routes/api/events/invalid/+server.ts
> +        WHERE id IN (${ids.map(() => "?").join(",")})
This is a nice idiom!

Not necessary and maybe less clear, but you can drop the `.join()`. That is the default behavior of stringifying an array.

Another way:
```ts
Array(ids.length).fill('?')
```

2023-11-12 22:48 UTC, rob-3 commented on repos/web/src/lib/query/queries.ts
> +  if (!navigator?.onLine) {
nit: The tiniest of nits, but I think this `?` is not needed

2023-11-12 22:57 UTC, rikimbili commented on repos/web/src/lib/query/queries.ts
> +  if (!navigator?.onLine) {
Couldn't navigator be undefined on the server?

2023-11-12 22:59 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +        <h1 class="text-xl font-bold">Error loading event &#128532;</h1>
nit: I believe it's ok to paste the emoji directly into the code as long as we mark our text-encoding as utf-8

2023-11-12 23:00 UTC, rob-3 commented on repos/web/src/lib/query/queries.ts
> +  if (!navigator?.onLine) {
Right but you check `if (!browser)` right before this

2023-11-12 23:02 UTC, rob-3 requested changes
I am finished reviewing everything. If you fix the blocking issues, this can be approved. Thanks for bearing with my slowish review on this one and the big design changes.

2023-11-12 23:02 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +        <h1 class="text-xl font-bold">Error loading event &#128532;</h1>
I've had issues when other people accidentally use a different encoding resulting in the emoji becoming an invalid character. I personally like only using ASCII in source code

2023-11-12 23:02 UTC, rikimbili commented on repos/web/src/lib/query/queries.ts
> +  if (!navigator?.onLine) {
Oh you are right

2023-11-12 23:04 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +        <h1 class="text-xl font-bold">Error loading event &#128532;</h1>
Good point

2023-11-12 23:13 UTC, rikimbili commented on repos/web/src/routes/api/events/+server.ts
> +});
This will result in us needing a defined type guard to check what part of the union the schema matches and might make validating the schema more convoluted. We cannot simply destructure parsed.data anymore without having a type guard before it:
```
TS2339: Property id and limit do not exist on type
{   id: string; } | {   limit?: number | undefined; }
```

2023-11-12 23:14 UTC, rikimbili commented on repos/web/src/routes/api/events/+server.ts
> +        ORDER BY ? ${orderDir}
yea we do have a bug here

2023-11-12 23:15 UTC, rob-3 commented on repos/web/src/routes/api/events/+server.ts
> +});
I would just do a `if ('id' in parsed.data)` and then you should have access to `parsed.data.id` in the branch

2023-11-12 23:18 UTC, rob-3 commented on repos/web/src/routes/api/events/+server.ts
> +});
The reason I don't like the existing schema is that it has the same issue as the function before - it would allow someone to call the endpoint with no id or limit.

2023-11-12 23:21 UTC, rob-3 commented on repos/web/src/routes/api/events/+server.ts
> +  const parsed = schema.safeParse(Object.fromEntries(url.searchParams.entries()));
No, but stackoverflow was warning that this approach doesn't give you number values in the object. Zod will parse them out though I believe

2023-11-12 23:22 UTC, rikimbili commented on repos/web/src/routes/api/events/+server.ts
> +});
Yea you are right, I just wasnt familiar with unions and that didn't come to mind. Thanks for recommending that approach

2023-11-12 23:26 UTC, rob-3 requested changes

2023-11-12 23:26 UTC, rob-3 commented on repos/web/src/routes/api/events/+server.ts
> +  z.object({ limit: z.coerce.number().int().nonnegative().optional() })
blocking: I think this should not be optional, right? Otherwise we are returning all events

2023-11-12 23:28 UTC, rob-3 commented on repos/web/src/routes/api/events/+server.ts
> +  z.object({ limit: z.coerce.number().int().nonnegative().optional() })
One thing I'm wondering if we should do in the future is use the `.prepare()` type args to help type safety a little.
```ts
db.prepare<number>(`SELECT * from event LIMIT ?`).get('hello') // Error!
```
What do you think?

2023-11-12 23:37 UTC, rikimbili commented on repos/web/src/routes/api/events/+server.ts
> +  z.object({ limit: z.coerce.number().int().nonnegative().optional() })
I think thats a good idea

2023-11-12 23:41 UTC, rob-3 approved these changes
Good work!

2023-11-12 23:41 UTC, merged