Filters Component
sdes-team/knightlife pull request #68
Opened 2023-11-18 16:31 UTC by rikimbili

2023-11-18 17:12 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +  export { allTags as tags };
blocking: This export isn't accessible outside of the component. You need to use a script tag with `context=module` if you want to export things from a component file.

2023-11-18 17:12 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +  export { allTags as tags };
Tbh this can just be deleted - I don't think it is used anywhere

2023-11-18 17:15 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +  };
nonblocking: You can consider a `satisfies` clause here like:
```ts
  $: filters = {
    weekday: null,
    tags: allTags.map((tag) => ({ value: tag, checked: false })),
    tagsCondition: "and" as "and" | "or",
    friendsGoing: false,
    freeAttendance: false
  } satisfies {
    weekday: number | null;
    tags: { value: string; checked: boolean }[];
    tagsCondition: "and" | "or";
    friendsGoing: boolean;
    freeAttendance: boolean;
  };
  ```
if you want to avoid the cast

2023-11-18 17:36 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +    goto(`/?${$page.url.searchParams.toString()}`, { invalidateAll: true, keepFocus: true });
nonblocking: This does add a "back" entry for every update to the query params. A debounce _could_ be a better experience to coalesce tag adds so someone doesn't have to go back for every added tag. We will definitely want this for the search query once that is implemented.
blocking: Put a TODO here for this

2023-11-18 17:41 UTC, rikimbili commented on repos/web/src/lib/components/input/Filters.svelte
> +  export { allTags as tags };
Sounds good, I'll add it back once I wire this component.

2023-11-18 17:44 UTC, rikimbili commented on repos/web/src/lib/components/input/Filters.svelte
> +    goto(`/?${$page.url.searchParams.toString()}`, { invalidateAll: true, keepFocus: true });
We could debounce the request itself at the parent component instead of here.

2023-11-18 17:46 UTC, rikimbili commented on repos/web/src/lib/components/input/Filters.svelte
> +    goto(`/?${$page.url.searchParams.toString()}`, { invalidateAll: true, keepFocus: true });
Actually nvm, it makes sense to debounce here. That way the URL history is not spammed when the user is selecting filters on top of preventing too many queries. I'll add the TODO.

2023-11-18 19:20 UTC, rikimbili commented on repos/web/src/lib/components/input/Filters.svelte
> +  };
Now I know how to use satisfies properly lol

2023-11-18 19:20 UTC, rikimbili commented on repos/web/src/lib/components/input/Filters.svelte
> +    goto(`/?${$page.url.searchParams.toString()}`, { invalidateAll: true, keepFocus: true });
I added the debounce (wasn't much work anyways)

2023-11-19 01:56 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +  };
This is actually not really what `satisfies` is for, it just is more convenient than [this](https://github.com/sveltejs/language-tools/blob/master/docs/preprocessors/typescript.md#how-do-i-type-reactive-assignments--i-get-an-implicitly-has-type-any-error)

2023-11-19 02:16 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +  };
So actually, unlearn everything you just saw, because `satisfies` actively doesn't work how we want here. `satisfies` will check that something is a subtype while retaining the most specific type that it can, which is not what we want here. We need to declare the variable with `let` and the type before the reactive declaration.

I also learned that Svelte spun out the actual component type-checking into a separate package, so the build doesn't notice this.

2023-11-22 01:39 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +                <Button href="#" variant="secondary" class="!rounded-full">
blocking: I don't think this needs to be `!important`

2023-11-22 01:48 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +                <Button href="#" variant="secondary" class="!rounded-full">
We do since Button already defines the roundness. I could also make the li tag be rounded instead of overriding the button style

2023-11-27 00:21 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +  export let appendedLabelId: string | undefined; // Used to avoid duplicate IDs
blocking: Is avoiding duplicates the only motivation here? Why not generate a UUID with `crypto.randomUUID()` and use that instead?

2023-11-27 00:26 UTC, rob-3 commented on repos/web/src/routes/+page.ts
> +  };
nonblocking: I do wonder if it would be better to bundle all of this state into one object

2023-11-27 00:28 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +    freeAttendance = false;
blocking: this is my bug, but I forgot to include `sortedBy` here

2023-11-27 00:31 UTC, rob-3 commented on repos/web/src/lib/data/filters.ts
> +export const weekdayList = ["S", "M", "T", "W", "T", "F", "S"];
nonblocking: I typically would include these types with the relevant component until I need to reuse them elsewhere. Up to you, but I usually consider that as a good [WET code practice](https://overreacted.io/the-wet-codebase/).

2023-11-27 00:32 UTC, rob-3 commented on repos/web/src/routes/+page.svelte
> +  let freeAttendance = data.filters.freeAttendance;
nonblocking: This destructures very nicely if you prefer

2023-11-27 00:36 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +                animate:flip={{ duration: 500 }}
nonblocking: this is a cool sort effect, but I think it's actually user hostile. I am just imagining my grandma chasing the moving tags around while they sort. My sister was annoyed by it also when I had her test it.

I think it would be better if we put a list of tags below with X next to each to remove and don't resort the list. Doesn't need to be in this PR though.

2023-11-27 00:37 UTC, rob-3 requested changes
See comments, just a couple minor things need to be fixed and this is good, at least for now. Sorry for the extended timeline on getting this reviewed

2023-11-27 01:06 UTC, rikimbili commented on repos/web/src/lib/components/input/Filters.svelte
> +                animate:flip={{ duration: 500 }}
That's what I had initially actually lol. Should have kept that implementation. I personally like this one more but I can see how some people might get annoyed with the auto sorting

2023-11-27 01:09 UTC, rikimbili commented on repos/web/src/lib/data/filters.ts
> +export const weekdayList = ["S", "M", "T", "W", "T", "F", "S"];
Yea I agree. My initial design involved reusing these but it's no longer the case

2023-11-27 01:10 UTC, rikimbili commented on repos/web/src/lib/components/input/Filters.svelte
> +    freeAttendance = false;
This is intended behavior. When we reset the filters, it shouldn't reset the sorting. Sorting is technically not part of the filters.

2023-11-27 01:12 UTC, rikimbili commented on repos/web/src/routes/+page.ts
> +  };
Are you saying to put everything inside of the filters object?

2023-11-27 01:14 UTC, rikimbili commented on repos/web/src/lib/components/input/Filters.svelte
> +  export let appendedLabelId: string | undefined; // Used to avoid duplicate IDs
I did that initially but it looks kinda ugly :P. I also tried to use the code from here https://github.com/rozek/locally-unique-id-generator to create a unique id similar to how react does it but had some issues.

2023-11-27 01:15 UTC, rob-3 commented on repos/web/src/routes/+page.ts
> +  };
I'm saying that _might_ be a good idea. I just notice that all of this data goes into the filters component anyways. But maybe this separation makes more logical sense, or maybe since we might want to handle `search` differently in the future, it should be separate.

This is a minor thing and probably we should just leave it and see

2023-11-27 01:15 UTC, rikimbili commented on repos/web/src/lib/components/input/Filters.svelte
> +  export let appendedLabelId: string | undefined; // Used to avoid duplicate IDs
I can just do randomUUID, no one cares about that anyways lol

2023-11-27 01:15 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +    freeAttendance = false;
Fair enough

2023-11-27 01:15 UTC, rob-3 commented on repos/web/src/routes/+page.svelte
> +  let freeAttendance = data.filters.freeAttendance;
If it works, I would do it

2023-11-27 01:21 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +  export let appendedLabelId: string | undefined; // Used to avoid duplicate IDs
You could only use the UUID if one isn't passed in. I guess I mainly just don't like how you're required to come up with a largely meaningless UUID to use the component

2023-11-27 01:22 UTC, rob-3 commented on repos/web/src/lib/components/input/Filters.svelte
> +  export let appendedLabelId: string | undefined; // Used to avoid duplicate IDs
I don't think the id is ever user-visible, even for accessibility

2023-11-27 03:19 UTC, rikimbili commented on repos/web/src/lib/data/filters.ts
> +export const weekdayList = ["S", "M", "T", "W", "T", "F", "S"];
We do use these in separate places. The Filters component and the load function

2023-11-28 00:56 UTC, rob-3 requested changes
The changes you've made don't stop the resorting on selection though, since you remove selected tags from the original list. Would you be opposed to keeping the selected tags in the main list also so they don't ever move?

2023-11-28 01:36 UTC, rikimbili commented
> The changes you've made don't stop the resorting on selection though, since you remove selected tags from the original list. Would you be opposed to keeping the selected tags in the main list also so they don't ever move?

I changed it again, lmk if it's better now

2023-11-28 03:22 UTC, rob-3 approved these changes

2023-11-28 03:29 UTC, merged