Initial addition of navigation bar
sdes-team/knightlife pull request #73
Opened 2023-11-22 05:14 UTC by danielagd

Additions: 
- logo.png
- default profile pic png
- logo addition
- profile tag drop down
- profile page

2023-11-22 05:23 UTC, rikimbili commented
We should use an icon as the default profile pic. We would just need to import it from Lucide, something from here https://lucide.dev/icons/?focus=&search=account

2023-11-22 05:31 UTC, rob-3 commented
> https://lucide.dev/icons/?focus=&search=account

Is it just me or do these guys also have broken deep linking? I feel like this is the 3rd or 4th site this week I've come across that doesn't implement this correctly.

2023-11-22 05:40 UTC, rikimbili commented
> > https://lucide.dev/icons/?focus=&search=account
> 
> Is it just me or do these guys also have broken deep linking? I feel like this is the 3rd or 4th site this week I've come across that doesn't implement this correctly.

Wow you are right, it is broken

2023-11-22 05:48 UTC, danielagd commented
> We should use an icon as the default profile pic. We would just need to import it from Lucide, something from here https://lucide.dev/icons/?search=account

I put it as an image so it can be replaced easily when a user wishes. that way it doesnt need to go from icon -> image and you just change the src

2023-11-22 05:51 UTC, rikimbili commented
> > We should use an icon as the default profile pic. We would just need to import it from Lucide, something from here https://lucide.dev/icons/?search=account
> 
> I put it as an image so it can be replaced easily when a user wishes. that way it doesnt need to go from icon -> image and you just change the src

Fair, I tend to do icon because it is served with the html of the page and is therefore way faster to load but we can keep it as an image for simplicity.

2023-11-22 06:00 UTC, rob-3 commented
If you prefer the performance of inline, you can base64-encode the image and serve it inline. I think this is not a huge problem either way

2023-11-22 06:32 UTC, rikimbili requested changes
Looks Great! Most of my requested changes are just minor CSS stuff.

2023-11-22 06:32 UTC, rikimbili commented on repos/web/src/lib/components/NavigationBar.svelte
> +        >Profile
Minor formatting issue, the > symbol should be in the same line as the < for the Button in this case. Prettier does this to me too and I have to fix it manually :(

2023-11-22 06:32 UTC, rikimbili commented on repos/web/src/lib/components/NavigationBar.svelte
> +      <Button builders={[builder]} class="rounded-full"
We might want to add to do `!rounded-full` with the exclamation. The reason is that Button internally has rounded-md set and while this looks fine in dev, it might not in production (I had this issue a couple times already). Plus it is not recommended to have two tailwind classes targeting the same property.

Also, this results in a look closer to what we have in the design: `class="!rounded-full !pl-3 !pr-0"`

And one more thing, I think variant="secondary" looks better here, what do you think?

2023-11-22 06:32 UTC, rikimbili commented on repos/web/src/routes/+page.svelte
> +<main class="block min-h-screen w-full max-w-7xl gap-4 p-4">
Is there a reason why we changed this to block instead of flex?

2023-11-22 06:32 UTC, rikimbili commented on repos/web/src/routes/+page.svelte
> +  <div class="w-full justify-center flex">
I think this div is not needed as long as we add justify-center and replace block with flex in the class of **main** so that it becomes `"flex min-h-screen w-full max-w-7xl justify-center gap-4 p-4"`

2023-11-22 06:32 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +<div class='w-full p-5 relative flex'>
No need to make it relative and we should set padding to 4 as to match the padding of the divs in main.

2023-11-22 06:32 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
I think the back button should be visible on larger screens (desktop) as well. We should set the variant to link `variant="link"`. We can remove `top-0 left-0`

2023-11-22 09:00 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
I actually suggested to hide it on large screens because it renders right next to the browser back button and seems redundant

2023-11-22 15:58 UTC, danielagd commented on repos/web/src/lib/components/NavigationBar.svelte
> +      <Button builders={[builder]} class="rounded-full"
I was also considering secondary, but the background seems too light and blends into the overall background. It's not as accessible so I kept it the original variant. If we change out minds about colors, it's an easy fix in the future.

2023-11-22 15:59 UTC, danielagd commented on repos/web/src/routes/+page.svelte
> +<main class="block min-h-screen w-full max-w-7xl gap-4 p-4">
No, I was playing around with the formatting and didn't catch to change it back to flex. Thank you!

2023-11-22 17:16 UTC, rob-3 commented on repos/web/src/routes/profile/+page.svelte
> +        navigator.serviceWorker.ready;
blocking: what does this do? It appears to be dead code.

2023-11-22 17:20 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
That is a good point, but the idea of this back button is to take you back even if someone gives you a link to this event. That's why I wanted to label it "See all events" or something like that

2023-11-22 17:25 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
Ah, this makes more sense. Maybe a home button/logo button would be more appropriate then? It's tough for me to get over the 2 duplicate back buttons in the corner

2023-11-22 17:26 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
The search params work should be finished in our PR; Dani or us and apply that here later.

2023-11-22 17:32 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
Using the logo as a "go to home" button is not a bad idea but I'm not sure how obvious that would be initially. I personally would like to have a back icon and a label next to it that says either "See all events" or "Go to feed" so that it clearly tells you what it does. We can also make that label be a tooltip for the logo button.

2023-11-22 17:35 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
It's a common pattern on a lot of sites, but I agree it has questionable discoverability.

Maybe a back button with "All Events"?

2023-11-22 17:35 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
Especially if you reverse the contrast so it's dark on light

2023-11-22 17:36 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
I like that. Short and clear.

2023-11-22 17:40 UTC, danielagd commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
Noted, will apply this now.

2023-11-22 17:43 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
> Especially if you reverse the contrast so it's dark on light

I don't personally think a back button should be a primary button. Setting the variant to link makes more sense (it shouldn't even be secondary). The reason is that we don't want to draw more focus to it, it is already at the very top of the page and the primary button is **RSVP** or **See Event** I think it's called on the app.

![image](https://github.com/sdes-team/knightlife/assets/39206666/605d54d0-16bd-44db-be71-69db063e88b8)
![image](https://github.com/sdes-team/knightlife/assets/39206666/bc2849b6-08ec-4e45-a4f1-7033cc04563f)

2023-11-22 17:45 UTC, danielagd commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
Also, we can do a home icon. I have also seen websites use that instead of an arrow with some text. Might also come across as more sleek

2023-11-22 17:47 UTC, rikimbili commented on repos/web/src/routes/event/[slug]/+page.svelte
> +  <Button href={'/'} size="sm" class="lg:hidden top-0 left-0">
> Also, we can do a home icon. I have also seen websites use that instead of an arrow with some text. Might also come across as more sleek

tbh thats how we did it in daydream and no one complained. We might as well do the same and just have a tooltip like I mentioned.

2023-11-23 03:36 UTC, rikimbili approved these changes

2023-11-23 05:50 UTC, rob-3 commented on repos/web/src/routes/event/[slug]/+page.svelte
> +          <div class="bg-muted h-10 w-10 rounded-lg p-2">
We should set up the repo so `npm run format` formats everything to how we want. I notice the lint doesn't see any problems, but `npm run format` does formatting on a bunch of config files and such.

2023-11-23 18:13 UTC, merged